apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cleanearth-rs
  labels:
    appname: cleanearth
    version: '1.0'
    team: qa
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: version
        operator: In
        values:
          - '1.0'
      - key: team
        operator: In
        values:
          - production
          - staging
  template:
    metadata:
      name: cleanearth
      labels:
        team: staging
        version: '1.0'
    spec:
      containers:
        - name: cleanearth-fe
          image: haikalrfadhilahh/cleanearth:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 1
            successThreshold: 1
            periodSeconds: 10
          


      