apiVersion: v1
kind: Namespace
metadata:
  name: cleanearth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanearth-fe-deployment
  namespace: cleanearth
  labels:
    app: cleanearth
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleanearth-fe
  template:
    metadata:
      labels:
        app: cleanearth-fe
    spec:
      containers:
        - name: cleanearth-fe
          image: ghcr.io/haikalrfadhilahh/cleanearth:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "2"
              memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cleanearth-fe-service
  namespace: cleanearth
  labels:
    app: cleanearth-fe
    type: frontend
spec:
  type: ClusterIP
  selector:
    app: cleanearth-fe
  ports:
    - port: 9090
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cleanearth-fe-ingress
  namespace: cleanearth
  labels:
    app: cleanearth-fe
    type: frontend
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cleanearth-fe-service
              port:
                number: 9090
