apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cleanearth-rs
  labels:
    team: front-end
    version: '1.0'
spec:
  replicas: 2
  selector:
    matchLabels:
      appname: cleanearth
  template:
    metadata:
      labels:
        appname: cleanearth
    spec:
      containers:
        - name: cleanearth
          image: haikalrfadhilahh/cleanearth:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 1
            successThreshold: 3

    
